// ─── ESTILOS ──────────────────────────────────────────────────────────────────
const S = {
  app: {
    minHeight: "100vh",
    background: "#0f0f1a",
    color: "#e8e8f0",
    fontFamily: "'Outfit','Segoe UI',sans-serif",
    display: "flex",
    flexDirection: "column",
  },
  authPage: {
    minHeight: "100vh",
    background: "#0f0f1a",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  authContainer: {
    display: "flex",
    width: "100%",
    maxWidth: 900,
    minHeight: 540,
    background: "#1a1a2e",
    borderRadius: 24,
    border: "1px solid #2a2a4a",
    overflow: "hidden",
  },
  authLeft: {
    flex: 1,
    minWidth: 260,
    background: "linear-gradient(145deg,#16213e,#0f3460)",
    padding: "48px 40px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
  },
  authLogo: {
    width: 56,
    height: 56,
    borderRadius: 16,
    background: "linear-gradient(135deg,#FF6B35,#FF3CAC)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 900,
    fontSize: 20,
    color: "#fff",
    marginBottom: 20,
  },
  authLogoMobile: {
    width: 48,
    height: 48,
    borderRadius: 14,
    background: "linear-gradient(135deg,#FF6B35,#FF3CAC)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 900,
    fontSize: 18,
    color: "#fff",
    margin: "0 auto 20px",
  },
  authBrandTitle: {
    fontSize: 26,
    fontWeight: 800,
    color: "#fff",
    margin: "0 0 10px",
  },
  authBrandSub: { fontSize: 14, color: "#8888bb", lineHeight: 1.6, margin: 0 },
  authRight: {
    flex: 1,
    padding: "40px 36px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    minWidth: 300,
  },
  onboardingCard: {
    background: "#1a1a2e",
    borderRadius: 24,
    padding: "40px 36px",
    width: "100%",
    maxWidth: 440,
    border: "1px solid #2a2a4a",
  },
  tabRow: {
    display: "flex",
    background: "#0f0f1a",
    borderRadius: 12,
    padding: 4,
    marginBottom: 24,
    gap: 4,
  },
  tabBtn: {
    flex: 1,
    padding: "10px 8px",
    background: "none",
    border: "none",
    color: "#8888bb",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    borderRadius: 9,
  },
  tabBtnActive: { background: "#1a1a2e", color: "#fff" },
  label: {
    display: "block",
    fontSize: 11,
    fontWeight: 700,
    color: "#8888bb",
    marginBottom: 6,
    marginTop: 16,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  input: {
    width: "100%",
    padding: "12px 14px",
    background: "#0f0f1a",
    color: "#e8e8f0",
    border: "1px solid #2a2a4a",
    borderRadius: 12,
    fontSize: 14,
    outline: "none",
    boxSizing: "border-box",
  },
  select: {
    width: "100%",
    padding: "12px 14px",
    background: "#0f0f1a",
    color: "#e8e8f0",
    border: "1px solid #2a2a4a",
    borderRadius: 12,
    fontSize: 14,
    outline: "none",
    boxSizing: "border-box",
  },
  roleRow: { display: "flex", gap: 10, marginTop: 8 },
  roleBtn: {
    flex: 1,
    padding: 10,
    background: "#0f0f1a",
    color: "#8888bb",
    border: "1px solid #2a2a4a",
    borderRadius: 10,
    fontSize: 13,
    cursor: "pointer",
  },
  roleBtnActive: {
    background: "rgba(255,107,53,0.15)",
    color: "#FF6B35",
    border: "1px solid rgba(255,107,53,0.4)",
  },
  primaryBtn: {
    width: "100%",
    padding: 14,
    background: "linear-gradient(135deg,#FF6B35,#FF3CAC)",
    color: "#fff",
    border: "none",
    borderRadius: 14,
    fontSize: 15,
    fontWeight: 700,
    cursor: "pointer",
    marginTop: 20,
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "14px 24px",
    background: "#1a1a2e",
    borderBottom: "1px solid #2a2a4a",
    position: "sticky",
    top: 0,
    zIndex: 10,
  },
  headerLeft: { display: "flex", alignItems: "center", gap: 12 },
  logo: {
    width: 36,
    height: 36,
    borderRadius: 10,
    background: "linear-gradient(135deg,#FF6B35,#FF3CAC)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 800,
    fontSize: 13,
    color: "#fff",
  },
  headerTitle: { fontWeight: 700, fontSize: 16, color: "#fff" },
  headerSub: { fontSize: 11, color: "#8888bb", marginTop: 1 },
  pointsBadge: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    background: "rgba(255,107,53,0.15)",
    border: "1px solid rgba(255,107,53,0.3)",
    borderRadius: 20,
    padding: "5px 12px",
  },
  pointsNum: { fontSize: 13, fontWeight: 700, color: "#FF6B35" },
  cartBadge: {
    background: "rgba(255,107,53,0.2)",
    border: "1px solid rgba(255,107,53,0.4)",
    borderRadius: 20,
    padding: "5px 12px",
    fontSize: 13,
    fontWeight: 700,
    color: "#FF6B35",
    cursor: "pointer",
  },
  main: { flex: 1, overflowY: "auto", paddingBottom: 80 },
  mainInner: {
    maxWidth: 1100,
    margin: "0 auto",
    padding: 24,
    boxSizing: "border-box",
  },
  nav: {
    position: "fixed",
    bottom: 0,
    left: 0,
    right: 0,
    background: "#12121f",
    borderTop: "1px solid #2a2a4a",
    padding: "6px 0",
    zIndex: 10,
  },
  navInner: {
    maxWidth: 1100,
    margin: "0 auto",
    display: "flex",
    justifyContent: "center",
  },
  navBtn: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 3,
    padding: "6px 14px",
    background: "none",
    border: "none",
    cursor: "pointer",
    borderRadius: 8,
  },
  navBtnActive: { background: "rgba(255,107,53,0.1)" },
  navIcon: { fontSize: 18 },
  navLabel: { fontSize: 10, color: "#8888bb" },
  sectionTitle: {
    fontSize: 13,
    fontWeight: 700,
    color: "#8888bb",
    textTransform: "uppercase",
    letterSpacing: 1.2,
    marginBottom: 12,
    marginTop: 24,
  },
  grid2: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill,minmax(260px,1fr))",
    gap: 12,
  },
  welcomeCard: {
    display: "flex",
    alignItems: "center",
    gap: 16,
    background: "linear-gradient(135deg,#1a1a2e,#16213e)",
    borderRadius: 16,
    padding: "20px 24px",
    border: "1px solid #2a2a4a",
  },
  welcomeName: { fontWeight: 700, fontSize: 20, color: "#fff" },
  statCard: {
    background: "#1a1a2e",
    border: "1px solid #2a2a4a",
    borderRadius: 14,
    padding: 20,
    textAlign: "center",
  },
  dishCard: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    background: "#1a1a2e",
    borderRadius: 12,
    padding: "14px 16px",
    border: "1px solid #2a2a4a",
  },
  dishName: { fontWeight: 600, fontSize: 14, color: "#e8e8f0" },
  rateBtn: {
    background: "rgba(255,107,53,0.15)",
    color: "#FF6B35",
    border: "1px solid rgba(255,107,53,0.3)",
    borderRadius: 8,
    padding: "7px 12px",
    fontSize: 12,
    fontWeight: 600,
    whiteSpace: "nowrap",
  },
  qtyBtn: {
    width: 32,
    height: 32,
    borderRadius: 8,
    background: "rgba(255,107,53,0.15)",
    border: "1px solid rgba(255,107,53,0.3)",
    color: "#FF6B35",
    fontSize: 18,
    fontWeight: 700,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  promoCard: { background: "#1a1a2e", borderRadius: 12, padding: 16 },
  promoName: { fontWeight: 700, fontSize: 15, color: "#fff" },
  badge: {
    fontSize: 10,
    fontWeight: 800,
    color: "#fff",
    padding: "3px 8px",
    borderRadius: 6,
    letterSpacing: 0.5,
  },
  orderCard: {
    background: "#1a1a2e",
    borderRadius: 12,
    padding: 16,
    border: "1px solid #2a2a4a",
  },
  rewardCard: {
    background: "#1a1a2e",
    border: "1px solid #2a2a4a",
    borderRadius: 16,
    padding: 20,
    textAlign: "center",
  },
  pointsCard: {
    background: "linear-gradient(135deg,#1a1a2e,#16213e)",
    border: "1px solid #2a2a4a",
    borderRadius: 20,
    padding: 28,
    textAlign: "center",
  },
  progressBar: {
    background: "#2a2a4a",
    borderRadius: 100,
    height: 6,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    background: "linear-gradient(90deg,#FF6B35,#FF3CAC)",
    borderRadius: 100,
    transition: "width 0.4s",
  },
  txRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "13px 0",
    borderBottom: "1px solid #1e1e3a",
  },
  profileHeader: {
    display: "flex",
    alignItems: "center",
    gap: 16,
    background: "#1a1a2e",
    borderRadius: 16,
    padding: 20,
    border: "1px solid #2a2a4a",
    marginBottom: 4,
  },
  avatar: {
    width: 56,
    height: 56,
    borderRadius: 16,
    background: "linear-gradient(135deg,#FF6B35,#FF3CAC)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 24,
    fontWeight: 800,
    color: "#fff",
    flexShrink: 0,
  },
  infoRow: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    padding: "13px 0",
    borderBottom: "1px solid #1e1e3a",
  },
  dangerBtn: {
    width: "100%",
    padding: 13,
    background: "rgba(255,107,107,0.1)",
    color: "#FF6B6B",
    border: "1px solid rgba(255,107,107,0.3)",
    borderRadius: 12,
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    marginTop: 24,
  },
  formCard: {
    background: "#1a1a2e",
    border: "1px solid #2a2a4a",
    borderRadius: 14,
    padding: 16,
  },
  adminBtn: {
    padding: "8px 12px",
    background: "rgba(255,107,53,0.1)",
    color: "#FF6B35",
    border: "1px solid rgba(255,107,53,0.2)",
    borderRadius: 8,
    cursor: "pointer",
    fontSize: 14,
  },
  emptyState: {
    textAlign: "center",
    padding: "32px 20px",
    color: "#4444aa",
    fontSize: 14,
    background: "#1a1a2e",
    borderRadius: 12,
    border: "1px solid #2a2a4a",
  },
  modalOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.8)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 100,
    padding: 20,
  },
  modal: {
    background: "#1a1a2e",
    borderRadius: 24,
    padding: "36px 28px",
    width: "100%",
    maxWidth: 400,
    textAlign: "center",
    border: "1px solid #2a2a4a",
  },
  toast: {
    position: "fixed",
    top: 20,
    left: "50%",
    transform: "translateX(-50%)",
    color: "#fff",
    padding: "11px 22px",
    borderRadius: 12,
    fontSize: 14,
    fontWeight: 600,
    zIndex: 200,
    boxShadow: "0 4px 20px rgba(0,0,0,0.4)",
    whiteSpace: "nowrap",
  },
};

export default S;
